### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by Ewan88** [ggez/ggez#1192]
Hi it seems like there are issues with the examples.

First of all the 'super_simple' example describes building a circle shape using Graphics::Mesh however the circle doesn't appear, only the blank window.

Then I tried the Hello World project but this one does not run because the font file cannot be located - as far as I can tell it should be getting it from the cargo manifest.

I tried copy/pasting the code over my own as I was typing out as I go to better understand each line but that also didn't seem to work in either case.

I'm a complete beginner so any help would be appreciated.

Thanks.

EDIT: Nevermind, I just realised there is a resources folder in the root directory that contains the .tff files. I am still curious about the circle however.

**Comment by a1phyr** [comment]
Hello ! 

Are you using `master` branch ? If so, you should try out `devel` which the latest version. Your bug should be fixed there.

**Comment by poppyseedDev** [comment]
I tried using the devel branch, as the display was not moving. I am curious if you could merge the devel branch maybe into the main branch that would be great! Thanks!

**Comment by Ewan88** [comment]
> Hello !
> 
> Are you using `master` branch ? If so, you should try out `devel` which the latest version. Your bug should be fixed there.

I tried the code for 01_super_simple.rs on devel branch just now but it doesn't seem to be any different from main. After including the necessary parts it still doesn't seem to be being rendered.

Just to clarify, is this an issue with the example files or somewhere in the source code? I am using the example files as a reference while using ggez as a dependency.

**Comment by nobbele** [comment]
it's source code, use `0.9.0-rc0` as your dependency

**Comment by Ewan88** [comment]
That fixed it, thanks!
