### ISSUE TITLE
devel branch is not compatible with osx

### ISSUE THREAD

**Issue by gigaroby** [ggez/ggez#486]
Trying to run any example fails because of Gilrs is incompatible with osx. Not sure if this is intended but if it is the README probably needs to be fixed to reflect this fact.

```bash
~/projects/ggez $ cargo run --example snake
   Compiling ggez v0.5.0 (...)
    Finished dev [unoptimized + debuginfo] target(s) in 8.86s
     Running `target/debug/examples/snake`
Error: GamepadError("Gamepad error: Gilrs does not support current platform.")
```

**Comment by icefoxen** [comment]
We're aware.  There's a [PR open](https://github.com/ggez/ggez/pull/481) that works around this but I want to mess around with it more before merging it.

**Comment by icefoxen** [comment]
This should be resolved with #487 ; if you feel like testing it and seeing how it works, please do so!

**Comment by maxdeviant** [comment]
@icefoxen I'm still seeing the issue on OSX when running against `devel`.

I'm have the `gamepad` module disabled, like so:

```rust
.conf(conf::Conf {
    modules: conf::ModuleConf {
        audio: true,
        gamepad: false,
    },
    ..Default::default()
})
```

But when I run my game I get this error:

```
thread 'main' panicked at 'Gamepad module disabled', /Users/maxdeviant/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/c5c6dcb/src/input/gamepad.rs:59:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: <ggez::input::gamepad::NullGamepadContext as ggez::input::gamepad::GamepadContext>::next_event
   7: ggez::event::run
   8: hitheryon::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start_internal
  13: main
```

It seems like we would want to skip over [this code](https://github.com/ggez/ggez/blob/devel/src/event.rs#L233-L246) if the module is disabled, no?

**Comment by maxdeviant** [comment]
I've opened #502 which should fix the issue.

**Comment by icefoxen** [comment]
Awesome, thank you!  I'm frankly still not 100% sure what the Correct Behavior for trying to use a non-disabled module should be.  Thanks for double-checking this.
