### ISSUE TITLE
[0.6.0rc1] GameError no longer implementing Send

### ISSUE THREAD

**Issue by V02460** [ggez/ggez#893]
`GameError` does no longer implement the auto trait `Send`. This means it can no longer be used over multiple threads and is no longer compatible with the *anyhow* crate. The breaking commit is f1df72273f6f205c459313535292b06a020f023b.

**To Reproduce**
Compare the docs to see that the Send auto trait was but is no longer implemented
RC0: https://docs.rs/ggez/0.6.0-rc0/ggez/error/enum.GameError.html#impl-Send
RC1: https://docs.rs/ggez/0.6.0-rc1/ggez/error/enum.GameError.html#impl-Send

**Expected behavior**
`GameError` implements `Send`.

**Hardware and Software:**
 - ggez version: 0.6.0rc1

**Comment by icefoxen** [comment]
FACK

I mean

Thanks for the bug report, I didn't realize that broke `Send`.  Weird though, considering all its contents are `Arc`'d.

**Comment by icefoxen** [comment]
Should be fixed.

**Comment by V02460** [comment]
Sorry to bring more bad news. It’s actually not fixed as `gilrs::Error` does not implement `Send`. Related, but technically its own bug: `Sync` is also required, but not there anymore for the same reasons.

**Comment by icefoxen** [comment]
Well I guess we just revert f1df72273f6f205c459313535292b06a020f023b and get on with life.  Done in ba163476ab5b2b7fb9cb6a99c43b2cc7e646bd3e
